def py_init() -> int: ...
def py_run(code: str) -> int: ...
def py_finalize() -> int: ...


py_init()
py_run("import sys, signal; print(sys.executable, sys.prefix, sys.argv, sys.version.split()[0], signal.getsignal(signal.SIGINT), flush=True)")
py_finalize()
