# error: too many levels of indentation
# CPython's tokenizer allows 99 levels of indentation
if 1:
 if 1:
  if 1:
   if 1:
    if 1:
     if 1:
      if 1:
       if 1:
        if 1:
         if 1:
          if 1:
           if 1:
            if 1:
             if 1:
              if 1:
               if 1:
                if 1:
                 if 1:
                  if 1:
                   if 1:
                    if 1:
                     if 1:
                      if 1:
                       if 1:
                        if 1:
                         if 1:
                          if 1:
                           if 1:
                            if 1:
                             if 1:
                              if 1:
                               if 1:
                                if 1:
                                 if 1:
                                  if 1:
                                   if 1:
                                    if 1:
                                     if 1:
                                      if 1:
                                       if 1:
                                        if 1:
                                         if 1:
                                          if 1:
                                           if 1:
                                            if 1:
                                             if 1:
                                              if 1:
                                               if 1:
                                                if 1:
                                                 if 1:
                                                  if 1:
                                                   if 1:
                                                    if 1:
                                                     if 1:
                                                      if 1:
                                                       if 1:
                                                        if 1:
                                                         if 1:
                                                          if 1:
                                                           if 1:
                                                            if 1:
                                                             if 1:
                                                              if 1:
                                                               if 1:
                                                                if 1:
                                                                 if 1:
                                                                  if 1:
                                                                   if 1:
                                                                    if 1:
                                                                     if 1:
                                                                      if 1:
                                                                       if 1:
                                                                        if 1:
                                                                         if 1:
                                                                          if 1:
                                                                           if 1:
                                                                            if 1:
                                                                             if 1:
                                                                              if 1:
                                                                               if 1:
                                                                                if 1:
                                                                                 if 1:
                                                                                  if 1:
                                                                                   if 1:
                                                                                    if 1:
                                                                                     if 1:
                                                                                      if 1:
                                                                                       if 1:
                                                                                        if 1:
                                                                                         if 1:
                                                                                          if 1:
                                                                                           if 1:
                                                                                            if 1:
                                                                                             if 1:
                                                                                              if 1:
                                                                                               if 1:
                                                                                                if 1:
                                                                                                 if 1:
                                                                                                  if 1:
                                                                                                   if 1:
                                                                                                    print(1)
